In [1]:
x=6
y=7

In [10]:
print(x+y)
print('Hola mundo en Jupyter')

13
Hola mundo en Jupyter


In [3]:
from scipy import linalg

In [4]:
import numpy as np

In [5]:
a = np.array([[1,0,3],[0,1,-2],[1,1,2]])

In [ ]:
a 

array([[ 1,  0,  3],
       [ 0,  1, -2],
       [ 1,  1,  2]])

In [7]:
linalg.det(a)

np.float64(0.9999999999999998)

In [8]:
b = linalg.inv(a)
np.dot(a,b)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.array([
            [3,2],
            [1,1]
           ])
b=np.array([8,3])
linalg.solve(a,b)




array([2., 1.])